### PR TITLE
Updated design and layout

### PR DESCRIPTION
**Pull request by jancborchardt**
Before & after, adjusting it generally in the manner of https://github.com/xMartin/grouptabs/pull/190, but moreover improving the information design of the website.

(Next step would be to add 2 nice screenshots, or even embed a quick video.)

image

### CODE REVIEW

**Comment by xMartin** [comment]
> Next step would be to add 2 nice screenshots, or even embed a quick video.

🙌 👍 🙏

**Comment by jancborchardt** [comment]
> > Next step would be to add 2 nice screenshots, or even embed a quick video.
> 
> :raised_hands: :+1: :pray:

Should we update to this first? :) Or if it’s blocked by https://github.com/xMartin/grouptabs/pull/190, what’s left to do there?

**Comment by xMartin** [comment]
I'd say it's blocked by the app design update, yes. What's left to do is probably in our Signal conversation ;)

I'd be very happy to merge the improved layout and content only.

**Comment by xMartin** [comment]
Do we really need a license for this page? ;)

**Comment by xMartin** [comment]
I reverted the color and button changes so we're not ahead of the app design. We can open a PR later for that based on the first commit of this branch.

@jancborchardt I really like the content and layout improvement and the addition of the dark mode! 👍  Finally merging those. Thanks!

**Pull request merged**
